server:
  port: 8090

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client=ERROR:


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qaz923923

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}